version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.8.1
  aws-cli: circleci/aws-cli@1.3.1
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      - image: 'cimg/node:14.18.2'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Front-End app
          command: |
            npm run frontend:deploy