version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.8.1
  aws-cli: circleci/aws-cli@1.3.1
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run: 
          name: install node@14.18.1
          command: |
              set +e         
              touch $BASH_ENV    
              curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
              echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
              echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
              echo nvm install 14.18.1 >> $BASH_ENV
              echo nvm alias default 14.18.1 >> $BASH_ENV
      - run:
          name: verify node version
          command: node --version
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Front-End app
          command: |
            npm run frontend:deploy
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Front-End app
          command: |
            npm run frontend:deploy