version: 2.1
orbs:
  node: circleci/node@4.8.1
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - run: 
          name: Install node@14.18.1
          command: |
              set +e         
              touch $BASH_ENV    
              curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
              echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
              echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
              echo nvm install 14.18.1 >> $BASH_ENV
              echo nvm alias default 14.18.1 >> $BASH_ENV
      - run:
          name: verify node version
          command: node --version
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - aws-cli/setup
      - run:
          name: Install EB Cli
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip3 install awsebcli
      - run:
          name: Front-End Deploy
          command: |
              npm run frontend:deploy
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy
workflows:
  install:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master